### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by TomasVotruba** [Happyr/TranslationBundle#13]
Readme is probably outdated, since "dimentions" option doesn't work.
                                                                                 
>  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
>  Unrecognized option "dimension" under "happyr_translation"   

How to set up bundle now?

**Comment by jarro** [comment]
I've put together a pull request with a patch I made for this a while ago.

**Comment by TomasVotruba** [comment]
Could you link it please?

**Comment by jarro** [comment]
https://github.com/Happyr/TranslationBundle/pull/15

**Comment by TomasVotruba** [comment]
@jarro Thank you!

**Comment by mastercoding** [comment]
Could you merge this? @Nyholm

**Comment by Nyholm** [comment]
Closed by #17. 
Thank you @jarro
