### ISSUE TITLE
"Send selected translations to SaaS" fails

### ISSUE THREAD

**Issue by TomasVotruba** [Happyr/TranslationBundle#14]
Even when I have added package "php-http/message", this error occurres when I click on "Send selected translations to SaaS" in the profiler.

> Http\Discovery\NotFoundException: No factories found. Install php-http/message to use Guzzle or Diactoros factories. in /var/www/hosts/mary-fashion.cz/vendor/php-http/discovery/src/FactoryDiscovery.php:20 Stack trace: #0 /var/www/hosts/mary-fashion.cz/vendor/php-http/discovery/src/MessageFactoryDiscovery.php(49): Http\Discovery\FactoryDiscovery::find() #1 /var/www/hosts/mary-fashion.cz/vendor/happyr/translation-bundle/src/Http/RequestManager.php(55): Http\Discovery\MessageFactoryDiscovery::find() #2

**Comment by Nyholm** [comment]
That is because a httplug issue. They are in beta. I'll update the dependencies shortly.

**Comment by Nyholm** [comment]
Do you mind reading the updated readme and  try again with dev-master? 

If it works for you I'll tag a new release.

**Comment by johndodev** [comment]
I think it's related,
```
Problem 1
    - Installation request for happyr/translation-bundle ^0.2.2 -> satisfiable by happyr/translation-bundle[0.2.2].
    - happyr/translation-bundle 0.2.2 requires php-http/httplug 1.0.0-beta -> no matching package found.
```

or with dev-master

```
Problem 1
    - Installation request for happyr/translation-bundle dev-master -> satisfiable by happyr/translation-bundle[dev-master].
    - happyr/translation-bundle dev-master requires php-http/client-implementation ^1.0 -> no matching package found.
```

Is it really required to down min-stability in composer ?

**Comment by damienalexandre** [comment]
It works with dev-master :+1: you can tag!

**Comment by Nyholm** [comment]
Thank you for the update. Ive tagged 0.3.0.

**Comment by TomasVotruba** [comment]
Thank you @Nyholm and @damienalexandre
