### ISSUE TITLE
Catchable Fatal Error: Argument 3 passed to GuzzleHttp\Client::request()

### ISSUE THREAD

**Issue by TuemmlerKon** [Happyr/TranslationBundle#2]
Got the following error while trying to upload an translation to loco:

    Catchable Fatal Error: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /home/tuemkode/www/bidgen/vendor/guzzlehttp/guzzle/src/Client.php on line 87 and defined

Also got this exception while trying to do a vendorupdate via composer:
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
Unrecognized option "dimensions" under "happyr_translation"
```

Regards

**Comment by kollegeJack** [comment]
Got it! Installing Bundle via Composer installs Guzzle6 instead of Guzzle5 so there should be the following in config.yml:

´´´
happyr_translation:
  http_adapter: 'guzzle6'
´´´

**Comment by morgenstern** [comment]
Got this error too and only found this issue after having solved it myself through switching back to guzzle 5.3 .. this is a way better solution. I suppose to 
a) catch the guzzle client error and show a message to mind this configuration
b) updated the docs with a hint to this error + configuration (maybe even update the defaults in the docs as guzzle 6.0+ will be used in most cases now).

**Comment by Nyholm** [comment]
I'm planning on update this to use [Httplug](http://docs.httplug.io/en/latest/) and PSR7 requests and responses. Just waiting on Httplug to be stable.

**Comment by morgenstern** [comment]
Great. Thank you. Until then I just created a PR to updated the README

**Comment by Nyholm** [comment]
That is awesome! Thank you for the PR.
