### ISSUE TITLE
How to implement this with no service?

### ISSUE THREAD

**Issue by clytemnestra** [Happyr/TranslationBundle#20]
Is there a way to not use any translation service, but to dump the translations in some files on the local machine?

**Comment by Nyholm** [comment]
That is interesting. It should be possible if we create a "Blackhole" service that implements `TranslationServiceInterface`. 
What do you think?

**Comment by clytemnestra** [comment]
I've tried to install it but it asks for phplug v1.0.0-beta. After trying to fix dependencies, it asks for one of the clients from [here](https://packagist.org/providers/php-http/client-implementation). I would've done [this gist](https://gist.github.com/damienalexandre/fa0d513d2fc832c132d0) myself, but thought this bundle might've already came with it so no reason to reinvent the wheel.

**Comment by Nyholm** [comment]
You are correct. Implementing a "Blackhole" service makes the dependency on Httplug optional.

**Comment by Nyholm** [comment]
You have a Blackhole service and a Filesystem service.

**Comment by clytemnestra** [comment]
Nice, I'll check it out when I'll have time.

**Comment by clytemnestra** [comment]
Managed to install and play a bit with it. Don't have time to fully configure it since I used jms/translation, but it's really nice to use the profiler, too. Might use it more in the future when I have time. Maybe even use with a service.
