### ISSUE TITLE
bundle not installable

### ISSUE THREAD

**Issue by johndodev** [Happyr/TranslationBundle#21]
Hello,

it seems there is no way to install the bundle with composer:

```
> composer require happyr/translation-bundle
Using version ^0.2.2 for happyr/translation-bundle                                
./composer.json has been updated
Loading composer repositories with package information                                                                                                                                                                Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for happyr/translation-bundle ^0.2.2 -> satisfiable by happyr/translation-bundle[0.2.2].
    - happyr/translation-bundle 0.2.2 requires php-http/httplug 1.0.0-beta -> no matching package found.
```

Tryed with dev-master

```
> composer update happyr/translation-bundle 
Loading composer repositories with package information                                                                                                                                                                Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - happyr/translation-bundle 0.2.2 requires php-http/httplug 1.0.0-beta -> no matching package found.
    - happyr/translation-bundle 0.2.1 requires php-http/httplug 1.0.0-beta -> no matching package found.
    - Installation request for happyr/translation-bundle ^0.2.1 -> satisfiable by happyr/translation-bundle[0.2.1, 0.2.2].
```

Tryed to install the four puli packages, they are downloaded but: 

```
Writing lock file
Generating autoload files
Warning: Plugin initialization failed: The "puli"/"puli.phar" command could not be found.

Fatal error: Call to a member function run() on null in /home/jplantey/www/geolid/geolid/vendor/puli/composer-plugin/src/PuliPluginImpl.php on line 671
```

and happyr/translation-bundle still not installable with thoses four packages.

Is it possible to do something please ?

**Comment by johndodev** [comment]
If you can't maintain the repo please write it in readme.md.

**Comment by Nyholm** [comment]
Hey @johndodev. 
Thank you for this issue and thank you for the feedback. Im sorry I (or nobody else) have replied to your issue. Any help maintaining this (or any repo) is always much appreciated. 

To your issue with installing the bundle. How far are you with debugging this?
* Have you tried with the latest changes of this bundle? `composer require happyr/translation-bundle:dev-master`
* Have you looked at the [Puli documentation](http://docs.puli.io/en/latest/)?
* Have you looked at the recent changes in [php-http/discovery](https://github.com/php-http/discovery) or read [the docs](http://docs.php-http.org/en/latest/discovery.html)?

From the error message you wrote: 
> Warning: Plugin initialization failed: The "puli"/"puli.phar" command could not be found.

It seams that you have not installed puli globally nor put the puli.phar in your application root. Is that correct?

The readme an possibly the composer.json probably should be updated so more people does not run in to this same issue. I would be happy to find this solution with you so we can improve the quality of this bundle.

**Comment by johndodev** [comment]
Hey,

I tryed with dev-master (it is the second code quote), but there is still errors.

I have briefly read some Puli doc, but as a lazy developper I don't really want to know all the detail of a bundle dependancies than I don't code myself. It seems Puli will be an interesting way of using PSR components but I am not comfortable with it and don't really want to at the moment. I think composer should abstract all this.

So, I saw the post saying the possibly removing of auto discovery things, it's up to you, but I think it will be good to "keep it simple", aka "composer require bundle and use it" ^^. It also will reduce the "installation" chapter of the readme, more user friendly !

**Comment by Nyholm** [comment]
Thank you for the feedback. 
I've merged the PRs and now you have to provide service names to your Http client and Message factory. (See the new [installation instructions](https://github.com/Happyr/TranslationBundle#install)) 

A suggested bundle is HttplugBundle which will help you with that. 

Does this solve your issue and does it make sense?

**Comment by johndodev** [comment]
The installation is working, I have another issue (Puli Factory is not available) but it is another subject.

I will work on it later, thanks !

**Comment by Nyholm** [comment]
Awesome. I've removed the need for Puli completely. As [DamienHarper said](https://github.com/Happyr/TranslationBundle/pull/23#issuecomment-188817306) you could use HttplugBundle to create services for your Httplug client.
