### ISSUE TITLE
Remove auto discovery feature

### ISSUE THREAD

**Issue by Nyholm** [Happyr/TranslationBundle#22]
We maybe should remove the auto discovery and let the user inject a Httpclient. That will make it easier to install the bundle and will make sure it is more light weight. 

Any thoughts?

**Comment by onlime** [comment]
+1

Just today I stumbled upon a "Puli Factory is not available" RuntimeException as the `PULI_FACTORY_CLASS` constant was not generated after a `composer require` - wasted some precious minutes.
I prefer not depending on Puli at all for the moment as AFAIK Puli is still not in widespread use.

If you decide to remove the auto discovery, please assure there is a nice configuration example for php-http/guzzle6-adapter in your [README.md](/Happyr/TranslationBundle/blob/master/README.md).

**Comment by Nyholm** [comment]
Fixed by #23
