### ISSUE TITLE
Non defined twig parameters in translation.twig after update

### ISSUE THREAD

**Issue by morgenstern** [Happyr/TranslationBundle#25]
After updating to latest dev-master I ran into the following issue:

Twig fails to render the translation view of the debug toolbar due to two missing parameters in this file: _/vendor/happyr/translation-bundle/src/Resources/views/Profiler/translation.html.twig_ 

Line 147: 
`{% if message.transChoiceNumber is not null %}`
Line 151: 
`{% if message.parameters|length > 0 %}`

I suppose the source of this error might be missing data from previous version. But an easy fix could be this: 

Line 147: 
`{% if message.transChoiceNumber is defined and message.transChoiceNumber is not null %}`
Line 151: 
`{% if message.parameters is defined and message.parameters|length > 0 %}`

Best
Helge

**Comment by Nyholm** [comment]
What version of Symfony are you using?

I like that change. Would you mind sending a PR?

**Comment by pitpit** [comment]
It seems "transChoiceNumber" is introduced in SF with commit https://github.com/symfony/translation/commit/f58e63092a312d76beebc633e4a6c63b3e63be5b released in symfony/symfony:2.8.0. However, your composer.json requires symfony/symfony:2.7.0 as minimal version

**Comment by pitpit** [comment]
I submitted a PR to fix this issue
