### ISSUE TITLE
Twig 2.0 error

### ISSUE THREAD

**Issue by istvankis** [Happyr/TranslationBundle#34]
Impossible to invoke a method ("render_table") on a string variable ("@HappyrTranslation/Profiler/translation.html.twig") in @HappyrTranslation/Profiler/translation.html.twig at line 63

**Comment by damienalexandre** [comment]
This looks like a Symfony issue, which version are you on?

**Comment by istvankis** [comment]
"symfony/symfony": "~3.0",
"happyr/translation-bundle": "~0.4"
with: "minimum-stability": "dev"

**Comment by Nyholm** [comment]
Closed by #37
