### ISSUE TITLE
Guzzle6: Passing in the "body" request option as an array to send a POST request has been deprecated.

### ISSUE THREAD

**Issue by morgenstern** [Happyr/TranslationBundle#4]
Hi Tobias, 

just wanted to let you know, that I discovered another issue when using guzzle 6 due to a deprecated usage of POST requests: 

Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.
https://github.com/guzzle/guzzle/blob/master/src/Client.php#L389

As you mentioned here https://github.com/Happyr/TranslationBundle/issues/2 you plan to switch to httplug. I suppose to remove the guzzle 6 requirement for this bundle and stick to guzzle 5.3 until then. 5.3 is working just fine for me so far. 

Thanks again for your work with this bundle!

**Comment by Nyholm** [comment]
Thank you for this. Yeah that is something I've missed. When using Httplug we will be sure to remove these differences with different adapters.

**Comment by Nyholm** [comment]
I've made some updates to this bundle. Does this issue still exists?

**Comment by Nyholm** [comment]
Im closing this due inactivity.
