### ISSUE TITLE
Lib php-http/client-implementation have new name now

### ISSUE THREAD

**Issue by igormukhingmailcom** [Happyr/TranslationBundle#41]
Hi.

Suppose this lib should be used: https://github.com/php-http/client-common
As far as `php-http/client-implementation` no longer available.

```
$ composer require happyr/translation-bundle:dev-master
...
  Problem 1
    - Installation request for happyr/translation-bundle dev-master -> satisfiable by happyr/translation-bundle[dev-master].
    - happyr/translation-bundle dev-master requires php-http/client-implementation ^1.0 -> no matching package found. <-------------------------------------
...
```

**Comment by Nyholm** [comment]
Hey. 

The `php-http/client-implementation` is a virtual package. You could install any of these: https://packagist.org/providers/php-http/client-implementation

Say you want to use Guzzle 6:
```
php composer.phar require php-http/guzzle6-adapter
```

Read more about it here: http://docs.php-http.org/en/latest/clients.html?highlight=virtual#composer-virtual-packages and here https://github.com/Happyr/TranslationBundle#install

**Comment by igormukhingmailcom** [comment]
Ah, thanks @Nyholm.
Was not aware of virtual packages.
I believe this link http://docs.php-http.org/en/latest/clients.html?highlight=virtual#composer-virtual-packages in README can save a lot of time to people that also not aware about this.
