### ISSUE TITLE
nonexistent keys in twig arrays

### ISSUE THREAD

**Issue by hoffereka** [Happyr/TranslationBundle#43]
Hi,
when I click on the profiler, translations, I get sometimes this:

Exception # \Twig_Error_Runtime: array(
	['message'] => 'Key "transChoiceNumber" for array with keys "locale, domain, id, translation, state, count" does not exist in "@HappyrTranslation/Profiler/translation.html.twig" at line 149',

If I put an "is defined and"... condition, the problem solved.

May I put a pull request?

**Comment by Nyholm** [comment]
Awesome. I'll be happy to review your PR.

**Comment by hoffereka** [comment]
Grrrrr. This already has been solved in dev-master on packagist. Sorry for wasting time.

**Comment by Nyholm** [comment]
No worries. I'm happy you take interest in the project.
