### ISSUE TITLE
InvalidArgumentException in Client.php line 402:

### ISSUE THREAD

**Issue by Raghava525** [Happyr/TranslationBundle#44]
Hi,
    Am using laravel 5. The composer values are 

"laravel/framework": "5.0.*",
"guzzlehttp/guzzle": "^6.2",

When I am trying to send the mail using swift mailer :
My code is:

$em_arr = Array();
$em_arr['to'] = $email;
$em_arr['name'] = $name;
$em_arr['subject'] = 'Forgot password';
$emailcontent = array('html'=> '');
				
$merg_vars = array();
$merg_vars['get_loan_offer'] = $get_loan_offer;
$merg_vars['reset_password_link'] = $reset_password_link;
$template_name = 'reset_password';
				
Mail::send('emails.emailsent', [], function($message) use ($em_arr, $merg_vars, $template_name)
{
	$headers = $message->getHeaders();
	$headers->addTextHeader('X-MC-Template', $template_name);
	$headers->addTextHeader('X-MC-MergeVars', json_encode($merg_vars));
	$message->to($em_arr['to'], $em_arr['name'])->subject($em_arr['subject']);
});

The issue I got :
InvalidArgumentException in Client.php line 402: Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.

Can you please what's went wrong in my code. Can you please provide solution to send an email.

**Comment by Nyholm** [comment]
Hey. Thank your for reporting this issue. But are you sure this is the correct repo?

This bundle has nothing to do with Laravel nor sending emails.

**Comment by tobias-nitsche** [comment]
Yes it's wrong repo. 

Pretty sure Upgrading your Laravel Version or downgrad Guzzle might help. Solution 1 might be practical.

https://github.com/laravel/framework/commit/599c4e15afa1c0ff9e1a783afcc4c239418a9c8c

See here, Laravel 5.3 uses form_params. 

But its Off-Topic, wrong repo.

**Comment by Raghava525** [comment]
Sorry . Its wrong rep to ask this question here. 
And thank you so much . It will be helpful answer for your side.
