### ISSUE TITLE
exception when sending selected translations to SaaS with Symfony 3.3

### ISSUE THREAD

**Issue by pborreli** [Happyr/TranslationBundle#49]
not sure if it's a bug Symfony side as 3.3.0 just came in.

The bug happens on "Send selected translations to SaaS" click 

```
Warning: array_intersect_key(): Argument #1 is not an array

in vendor/happyr/translation-bundle/src/Controller/ProfilerController.php (line 208)
$toSave = array_intersect_key($dataCollector->getMessages(), array_flip($selected));
``` 
$dataCollector->getMessages() is a Symfony\Component\VarDumper\Cloner\Data object instead of the expected array

**Comment by Nyholm** [comment]
It is not a bug on the Symfony side, it is a feature... or.. 
Symfony started to use the `Data` object. 

See the fix here: https://github.com/php-translation/symfony-bundle/pull/96
I would be happy to merge a PR to this bundle. 

Btw, I will soon deprecate this bundle in favor of PHP-translation.

**Comment by pborreli** [comment]
Thanks for your feedback, I wasn't aware of this PHP-translation bundle, my bad !

**Comment by pborreli** [comment]
thanks, i migrated to PHP-translation since, but I'm sure it will help others 👍
