### ISSUE TITLE
Support for Symfony Flex

### ISSUE THREAD

**Issue by tarlepp** [Happyr/TranslationBundle#55]
It seems that currently bundle has following:
```
"sensio/framework-extra-bundle": "^2.7 || ^3.0"
```

And with flex projects it'll actually install ```^5.0``` version of that sensio/framework-extra-bundle

**Comment by Nyholm** [comment]
Hey. 
Nice you found me on Github =)

This bundle will be deprecated in favour of [php-translation](php-translation.readthedocs.io). I will make sure to do that within the next week or so.

**Comment by tarlepp** [comment]
@Nyholm damn I just take wrong bundle to test with :D Will move to php-translation, thanks!
